default:
  tags:
    - shared-windows
    - windows
    - windows-1809

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: test
  script:
    - npm ci
    - npm run bundle

test:
  stage: test
  script:
    - npm ci
    - npm test
