image: sndst00m/vscode-textmate-languageservice

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 0

cache:
  paths:
  - node_modules/

stages:
- build

build:
  stage: build
  script:
  - ./build
  artifacts:
    paths:
    - test/data/
