image: bluemixcode/node-xvfb

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 0

cache:
  paths:
  - node_modules/

stages:
- build

build:
  stage: build
  script:
    - xvfb-run -a npm test
  before_script:
    - npm install
  artifacts:
    paths:
    - test/data/
