.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- test

test:
  extends:
  - .shared_windows_runners
  stage: test
  script: npm install-test
  artifacts:
    paths:
    - test/data/
