default:
  tags:
    - shared-windows
    - windows
    - windows-1809

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm ci
    - npm run build

test:
  stage: test
  script:
    - npm ci
    - npm test
