image: cinatic/xvfb_node

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 0

cache:
  paths:
  - node_modules/

stages:
- build

build:
  stage: build
  script:
    - export DISPLAY=:9.0 Xvfb -ac -screen scrn 1024x768x24 :9.0 &
    - xvfb-run -a npm test
  artifacts:
    paths:
    - test/data/
