'use strict';

import * as vscode from 'vscode';

import { deepEqual } from './assert';
import { loadJsonFile } from './factory';
import { writeJsonFile, getComponentSampleDataUri } from './files';
import { jsonify } from './jsonify';

type Object = Record<number | string | symbol, any>;

// The API for runtime detection is frankly not sane.
// This is the best way to detect if we are in a web runtime.
// microsoft/vscode#104436; microsoft/vscode#134568
const isWebUI = vscode.env.uiKind === vscode.UIKind.Web;
const isRemote = typeof vscode.env.remoteName === 'string';
export const isWebRuntime = isWebUI && !isRemote;

/**
 * Generate test pass for a VS Code language provider's output vs a sample MATLAB class.
 * @param {vscode.ExtensionContext} context 
 * @param {string} component Name of callee test object component - `src\*.js`.
 * @param {string} sample Basename of target sample file - `data\*\*\*.json`.
 * @param {object[]} output Result array generated by component test.
 */
export async function pass(context: vscode.ExtensionContext, component: string, basename: string, output: Object[]) {
	const data = getComponentSampleDataUri.call(context, component, basename);
	const filepath = `./test/data/${component}/${basename}.json`;
	let stat: vscode.FileStat | void;

	// Check if file exists.
	try {
		stat = await vscode.workspace.fs.stat(data);
	// eslint-disable-next-line no-empty
	} catch (_) {}

	const expectedJson = await loadJsonFile(data);
	const outputJson = jsonify(output);

	// Run JSON diff assert and record error.
	let error: TypeError | void;
	try {
		deepEqual(outputJson, expectedJson, filepath)
	} catch (e) {
		error = e as TypeError;
	}

	// In Node runtime, dump output to data component subdirectory.
	if (!isWebRuntime && error) {
		await writeJsonFile(data, outputJson);
	}

	// In web runtime, dump output to terminal console (web runtime).
	if (isWebRuntime && error) {
		console.log(`${filepath} expected contents:`);
		console.log('');
		console.log(`    ${JSON.stringify(expectedJson)}`);
		console.log('');
		console.log(`${filepath} actual contents:`)
		console.log('');
		console.log(`    ${JSON.stringify(outputJson)}`);
		console.log('');
	}

	// Throw an uncaught exception to exit Mocha test closure.
	if (error) {
		throw error;
	}
}
