'use strict';

// @ts-check
const peggy = require('peggy');
const prettier = require('prettier');
const fs = require('fs');
const typescript = require('typescript');

const filePath = './src/scopes/parser.ts';
let parserText = fs.readFileSync('./src/scopes/parser.pegjs', 'utf8');

const pegconfig = {
	'plugins': [require('ts-pegjs')],
	output: 'source',
	cache: false,
    format: 'commonjs',
};

const pegconfigJson = require('../src/scopes/pegconfig.json');
Object.assign(pegconfig, pegconfigJson);
pegconfig.skipTypeComputation = true;
pegconfig.customHeader = '';
pegconfig.tspegjs = {};
pegconfig.tspegjs.customHeader = fs.readFileSync('./src/scopes/header.ts');

parserText = peggy.generate(parserText, pegconfig);

parserText = parserText.replace(/\/\/ @ts-ignore\n/g, '');
parserText = parserText.replace(/^import \b/m, 'import * as ');
parserText = parserText.replace(/^type \b/gm, 'export type ');

parserText = parserText.replace(/(?<=function peg\$computeLocation\([^\)]+)\)/,  '?)');
parserText = parserText.replace(/(?<=function peg\$SyntaxError\([^)]+\))/,  ': void');

parserText = parserText.replace('// Generated by Peggy 3.0.2.', '');
parserText = parserText.replace(/\/\/$/m, '');
parserText = parserText.replace('// https://peggyjs.org/', '');

const prettierrcJson = require('../.prettierrc.json');
parserText = prettier.format(parserText, prettierrcJson);

fs.writeFileSync(filePath, parserText);
