name: CI

concurrency: vscode_environment

on:
  push:
    branches: [ release-candidate/* ]
  pull_request:
    branches: [ main, release-candidate/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Use Node 20
      uses: actions/setup-node@v1
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: xvfb-run --server-args "-screen 0 1920x1080x24" npm test
    - name: Upload Data Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vscode-textmate-languageservice-test-data
        path: test/data
